[tools]
"aqua:LuaLS/lua-language-server" = "latest"
deno = "latest"
gcloud = "latest"
go = "latest"
gopls = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"
"npm:difit" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:zenn-cli" = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[env]
DISABLE_AUTOUPDATER = "1"
